// Pass 5A evidence: generates the proof worlds and writes plan views and a report to docs/world/evidence/pass5a/.
//   node tools/hillink-world/procgen/evidence.mjs
// Everything here is reproducible from the seeds below; rerunning overwrites the files with identical content.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createWorld, placeCapability, setConstruction, replayWorld, worldFingerprint, summary } from './world.mjs';
import { buildNav, validateNav, route, nodeFor } from './nav.mjs';
import { represent } from './themes.mjs';
import { scaleReport, DIMS } from './units.mjs';
import { serializeWorld, deserializeWorld } from './persist.mjs';
import { renderSvg } from './svg.mjs';

const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../docs/world/evidence/pass5a');
fs.mkdirSync(out, { recursive: true });
const write = (name, text) => fs.writeFileSync(path.join(out, name), text);
const report = [];
const line = s => report.push(s);

// The tiny seed world, in both themes.
const seed = createWorld({ seed: 'hillink' });
for (const theme of ['real', 'fantasy']) {
  write(`seed-${theme}-world.svg`, renderSvg(seed, { theme, frame: 'world', labels: false, width: 1000 }));
  write(`seed-${theme}-settlement.svg`, renderSvg(seed, { theme, frame: 'settlement', width: 1000 }));
  write(`seed-${theme}-building.svg`, renderSvg(seed, { theme, frame: Object.keys(seed.buildings)[0], nav: true, width: 1000 }));
}
const s = summary(seed);
line('# Pass 5A evidence (generated by procgen/evidence.mjs)');
line('');
line('## The seed world ("hillink")');
line('');
line(`- Fingerprint \`${s.fingerprint}\`, map ${s.mapMetres} × ${s.mapMetres} m, **${s.developedShare}% developed**.`);
line(`- Land: ${s.districts} district of ${s.parcels.total} parcels, ${s.parcels.developed} in use. ${s.roads} road, ${s.paths} path. ${s.environmentAnchors} scenery anchors in the wilderness.`);
line(`- One building ${s.buildings[0].footprint}, ${s.rooms} rooms, ${s.doors} doors; the stair core is reserved (one storey).`);
const real = new Map(represent(seed, 'real').items.map(i => [i.canonicalId, i.label])), fantasy = new Map(represent(seed, 'fantasy').items.map(i => [i.canonicalId, i.label]));
line('');
line('| Capability | Space | Real | Fantasy |');
line('|---|---|---|---|');
for (const c of Object.values(seed.capabilities)) line(`| ${c.id} | ${c.placement.spaceId} (${seed.spaces[c.placement.spaceId].rect.w}×${seed.spaces[c.placement.spaceId].rect.h} m) | ${real.get(c.placement.spaceId)} | ${fantasy.get(c.placement.spaceId)} |`);
const b = Object.values(seed.buildings)[0];
line(`| (building) | ${b.id} | ${real.get(b.id)} | ${fantasy.get(b.id)} |`);
line(`| (road) | ${Object.keys(seed.roads)[0]} | ${real.get(Object.keys(seed.roads)[0])} | ${fantasy.get(Object.keys(seed.roads)[0])} |`);

// A. determinism and B. variation.
line('');
line('## Determinism and variation');
line('');
line(`- "hillink" generated twice: ${worldFingerprint(createWorld({ seed: 'hillink' })) === s.fingerprint ? 'identical' : 'DIFFERENT'} (\`${s.fingerprint}\`).`);
line('');
line('| Seed | Fingerprint | Building | Front | Rooms (band L / R widths) | Road bends | Navigation |');
line('|---|---|---|---|---|---|---|');
for (const x of ['hillink', 'alpha', 'bravo', 'charlie', 'delta', 'echo']) {
  const w = createWorld({ seed: x }), bb = Object.values(w.buildings)[0];
  line(`| ${x} | \`${worldFingerprint(w).slice(0, 12)}\` | ${bb.footprint.w}×${bb.footprint.h} m at (${bb.footprint.x}, ${bb.footprint.y}) | ${bb.front} | ${bb.plan.bl} / ${bb.plan.br} m | ${Object.values(w.roads)[0].points.length - 2} | ${validateNav(w).ok ? 'valid' : 'INVALID'} |`);
  if (x === 'alpha' || x === 'bravo') write(`variation-${x}-real-settlement.svg`, renderSvg(w, { theme: 'real', frame: 'settlement', width: 1000 }));
}

// D. scale.
line('');
line('## Scale (metres; 1 person = 1.75 m = world/scale.mjs AGENT_HEIGHT)');
line('');
line(`- Person ${DIMS.person.height} m, footprint ${DIMS.person.footprint.w}×${DIMS.person.footprint.d} m. Door ${DIMS.door.width}×${DIMS.door.height} m, entrance ${DIMS.entrance.width}×${DIMS.entrance.height} m. Storey ${DIMS.storey} m (clear ${DIMS.clearHeight} m).`);
line(`- Corridor ${DIMS.corridor} m, smallest room ${DIMS.room.minSide} m a side, stair core ${DIMS.stairCore.w}×${DIMS.stairCore.d} m. Road ${DIMS.road.width} m (lane ${DIMS.road.lane} m), path ${DIMS.path.width} m, car ${DIMS.vehicle.length}×${DIMS.vehicle.width} m.`);
line(`- Checks: ${Object.entries(scaleReport()).map(([k, v]) => `${k} ${v ? 'yes' : 'NO'}`).join(', ')}.`);

// E. navigation.
const nav = buildNav(seed);
line('');
line('## Navigation (seed world)');
line('');
line(`- ${nav.nodes.size} nodes, ${nav.edges.length} edges, validation: ${validateNav(seed, nav).ok ? 'valid (every edge inside one space, doors on shared walls, everything reachable)' : 'INVALID'}.`);
for (const c of Object.values(seed.capabilities)) { const r = route(nav, nav.arrival, nodeFor(nav, c.placement.spaceId)); line(`- Map edge → ${c.id}: ${r.nodes.length} nodes, ${Math.round(r.cost)} m.`); }

// G. expansion with unknown capabilities, then F. persistence and replay.
const grown = createWorld({ seed: 'hillink' });
line('');
line('## Growth with capabilities the seed world never heard of');
line('');
line('| Capability | Requirements | Planner chose | Why | Feasible options considered |');
line('|---|---|---|---|---|');
for (const u of [
  { id: 'podcast-studio', area: 8, traits: ['quiet', 'recording'] },
  { id: 'drone-lab', area: 30, access: 'secure', traits: ['machines', 'flight'] },
  { id: 'test-track', outdoor: true, vehicles: true, area: 900, traits: ['vehicles'] },
  { id: 'archive', kind: 'archive' },
  { id: 'training-hall', area: 60, traits: ['gathering'] },
  { id: 'upper-lab', area: 40, level: 'any', traits: ['inspection'] },
  { id: 'robot-foundry', area: 140, traits: ['machines', 'making'] },
]) {
  const r = placeCapability(grown, u);
  setConstruction(grown, u.id, 'built');
  const feasible = r.plan.considered.filter(c => c.feasible).map(c => c.option);
  line(`| ${u.id} | ${u.outdoor ? 'outdoor, ' : ''}${u.area ?? 'default'} m²${u.access ? `, ${u.access}` : ''} | ${r.plan.chosen.option} → ${r.plan.chosen.target} | ${r.plan.chosen.reason} | ${[...new Set(feasible)].join(', ')} |`);
}
const g = summary(grown);
line('');
line(`After growth: ${g.buildings.length} buildings, ${g.rooms} rooms, ${g.parcels.developed}/${g.parcels.total} parcels, ${g.districts} district(s), **${g.developedShare}% developed**, navigation ${validateNav(grown).ok ? 'valid' : 'INVALID'}.`);
for (const theme of ['real', 'fantasy']) write(`grown-${theme}-settlement.svg`, renderSvg(grown, { theme, frame: 'settlement', width: 1000 }));
const saved = serializeWorld(grown), loaded = deserializeWorld(saved);
line('');
line('## Persistence and replay');
line('');
line(`- Saved ${Math.round(saved.length / 1024)} KB; reloaded fingerprint ${worldFingerprint(loaded) === worldFingerprint(grown) ? 'identical' : 'DIFFERENT'} (\`${worldFingerprint(grown)}\`).`);
line(`- Rebuilt from its ${grown.history.length}-entry history alone: ${worldFingerprint(replayWorld(grown.history)) === worldFingerprint(grown) ? 'identical' : 'DIFFERENT'}.`);
write('README.md', report.join('\n') + '\n');
console.log(report.join('\n'));
