// Writes the Help Center seed migrations from lib/help/seed-content.ts:
// - 20260928000610_help_center_seed.sql inserts articles whose slug doesn't exist yet.
// - 20260928000710_help_center_updates.sql rewrites SEED_UPDATED_SLUGS in databases that already had
//   the first seed, skipping any article an admin has edited (updated_by is set).
// Run: node --experimental-strip-types --no-warnings scripts/generate-help-seed.ts
import { writeFileSync } from "node:fs";
import { SEED_ARTICLES, SEED_UPDATED_SLUGS, SEED_VERIFIED_AT } from "../lib/help/seed-content.ts";
import { validateArticleInput } from "../lib/help/validate.ts";

const OUT = "supabase/migrations/20260928000610_help_center_seed.sql";
const UPDATES_OUT = "supabase/migrations/20260928000710_help_center_updates.sql";

// Dollar quoting with a tag that can't appear in the text, so article text needs no escaping.
function lit(value: string): string {
  let tag = "h";
  while (value.includes(`$${tag}$`)) tag += "h";
  return `$${tag}$${value}$${tag}$`;
}
const arr = (values: string[]) => (values.length ? `array[${values.map(lit).join(", ")}]::text[]` : "'{}'::text[]");

const slugs = new Set<string>();
const rows: string[] = [];
const rowBySlug = new Map<string, string>();
for (const { verified_at, ...article } of SEED_ARTICLES) {
  const checked = validateArticleInput({ ...article, last_verified_at: verified_at ?? SEED_VERIFIED_AT } as Record<string, unknown>);
  if (!checked.ok) throw new Error(`${article.slug}: ${checked.error}`);
  const a = checked.value;
  if (slugs.has(a.slug)) throw new Error(`duplicate slug ${a.slug}`);
  slugs.add(a.slug);
  const row =
    `  (${[
      lit(a.slug),
      lit(a.category),
      lit(a.title),
      lit(a.short_answer),
      lit(a.body),
      arr(a.steps),
      lit(a.audience),
      lit(a.status),
      a.feature ? lit(a.feature) : "null",
      arr(a.keywords),
      arr(a.question_variants),
      arr(a.related_slugs),
      String(a.featured),
      String(a.escalation_required),
      String(a.sort_order),
      `'${a.last_verified_at}'::timestamptz`,
    ].join(", ")})`;
  rows.push(row);
  rowBySlug.set(a.slug, row);
}
for (const slug of SEED_UPDATED_SLUGS) {
  if (!rowBySlug.has(slug)) throw new Error(`SEED_UPDATED_SLUGS has unknown slug ${slug}`);
}

for (const article of SEED_ARTICLES) {
  for (const related of article.related_slugs || []) {
    if (!slugs.has(related)) throw new Error(`${article.slug} links to missing article ${related}`);
  }
  for (const [, path] of (article.body || "").matchAll(/\]\((\/help\/[^)]+)\)/g)) {
    const slug = path.split("/")[3];
    const target = SEED_ARTICLES.find((x) => x.slug === slug);
    if (!target || `/help/${target.category}/${target.slug}` !== path) throw new Error(`${article.slug} has a broken link ${path}`);
  }
}

const sql = `-- Starter Help Center articles. Generated by scripts/generate-help-seed.ts from lib/help/seed-content.ts; don't edit by hand.
-- Run after 20260928000600_help_center.sql. Articles that already exist (by slug) are left alone,
-- so running this again never overwrites edits made in the admin editor.

insert into public.help_articles
  (slug, category, title, short_answer, body, steps, audience, status, feature, keywords, question_variants, related_slugs, featured, escalation_required, sort_order, last_verified_at)
values
${rows.join(",\n")}
on conflict (slug) do nothing;
`;

writeFileSync(OUT, sql);
console.log(`Wrote ${rows.length} articles to ${OUT}`);

const COLUMNS = ["category", "title", "short_answer", "body", "steps", "audience", "status", "feature", "keywords", "question_variants", "related_slugs", "featured", "escalation_required", "sort_order", "last_verified_at"];
const updates = `-- Help Center article updates. Generated by scripts/generate-help-seed.ts from lib/help/seed-content.ts; don't edit by hand.
-- Run after 20260928000610_help_center_seed.sql. Adds new articles and rewrites changed ones, but never
-- touches an article an admin has edited in the editor (updated_by is set). Safe to run again.

insert into public.help_articles
  (slug, ${COLUMNS.join(", ")})
values
${SEED_UPDATED_SLUGS.map((slug) => rowBySlug.get(slug)).join(",\n")}
on conflict (slug) do update set
${COLUMNS.map((c) => `  ${c} = excluded.${c}`).join(",\n")}
where help_articles.updated_by is null
  and (${COLUMNS.map((c) => `help_articles.${c}`).join(", ")})
      is distinct from (${COLUMNS.map((c) => `excluded.${c}`).join(", ")});
`;
writeFileSync(UPDATES_OUT, updates);
console.log(`Wrote ${SEED_UPDATED_SLUGS.length} article updates to ${UPDATES_OUT}`);
