-- Starter Help Center articles. Generated by scripts/generate-help-seed.ts from lib/help/seed-content.ts; don't edit by hand.
-- Run after 20260928000600_help_center.sql. Articles that already exist (by slug) are left alone,
-- so running this again never overwrites edits made in the admin editor.

insert into public.help_articles
  (slug, category, title, short_answer, body, steps, audience, status, feature, keywords, question_variants, related_slugs, featured, escalation_required, sort_order, last_verified_at)
values
  ($h$what-is-hillink$h$, $h$getting-started$h$, $h$What is HILLink?$h$, $h$HILLink connects local businesses with college athletes. Businesses post campaigns, athletes join and create posts, and athletes get paid once the business approves their work.$h$, $h$## How it works in one minute

- **Businesses** post campaigns: for example, "visit our restaurant and post about it on Instagram."
- **Athletes** browse campaigns near them, join the ones they qualify for, and do the work.
- The athlete sends a link to the live post as **proof**.
- The business **approves** the proof, and the athlete is **paid** through Stripe.

Everything happens inside your HILLink dashboard. You'll get notifications as each step happens.

## Where to go next

- Athletes: [Start here for athletes](/help/getting-started/athlete-start-here)
- Businesses: [Start here for businesses](/help/getting-started/business-start-here)$h$, '{}'::text[], $h$both$h$, $h$live$h$, $h$platform$h$, array[$h$about$h$, $h$overview$h$, $h$nil$h$, $h$how does hillink work$h$, $h$platform$h$]::text[], array[$h$How does HILLink work?$h$, $h$What does HILLink do?$h$]::text[], '{}'::text[], true, false, 5, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$campaign-types$h$, $h$campaign-types$h$, $h$What campaign types are there?$h$, $h$There are four campaign types: Instagram Post, Dine and Post, Product Review / Unboxing, and Monthly Ambassador.$h$, $h$## Instagram Post
Post about the business on Instagram. Formats: feed post, story, reel or carousel. Athletes usually have 3 days to post.

## Dine and Post
Visit the business (for example, eat at a restaurant), then post about it. Formats: feed post, story, reel, or a post plus a story. Usually 3 days to post.

## Product Review / Unboxing
Receive or pick up a product, then post a review or unboxing. Formats include feed post, story, reel, unboxing video or product review video. Usually 7 days to post.

## Monthly Ambassador
A longer partnership with several posts over about a month. The business picks which athletes join.

Each campaign lists exactly what to post, how many posts, the deadline and what proof is needed.$h$, '{}'::text[], $h$both$h$, $h$live$h$, $h$campaign_templates$h$, array[$h$instagram$h$, $h$dine and post$h$, $h$product review$h$, $h$unboxing$h$, $h$ambassador$h$, $h$templates$h$, $h$formats$h$, $h$reel$h$, $h$story$h$]::text[], array[$h$What kinds of campaigns are there?$h$, $h$What is a Dine and Post campaign?$h$]::text[], array[$h$how-campaigns-work$h$, $h$how-to-create-a-campaign$h$]::text[], false, false, 10, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-referrals-work$h$, $h$referrals$h$, $h$How do referral codes work?$h$, $h$Every HILLink account has its own referral code (it looks like HL-XXXX-XXXX) in Settings. If someone referred you, you can enter their code once in Settings.$h$, $h$- You can enter a referral code **only once**, and it can't be changed afterward.
- You can't use your own code.
- If a code doesn't work, check it for typos. Codes are not case sensitive.$h$, array[$h$Open Settings from your dashboard.$h$, $h$Find your referral code and tap Copy to share it.$h$, $h$If someone referred you, type their code in the referral field and save it.$h$]::text[], $h$both$h$, $h$live$h$, $h$referrals$h$, array[$h$referral$h$, $h$refer$h$, $h$invite$h$, $h$code$h$, $h$friend$h$, $h$hl-$h$]::text[], array[$h$Where is my referral code?$h$, $h$How do I refer a friend?$h$, $h$How do I enter a referral code?$h$]::text[], '{}'::text[], false, false, 10, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$account-pending-approval$h$, $h$troubleshooting$h$, $h$Why does my account say it's pending?$h$, $h$HILLink reviews every new athlete and business account before it can use the dashboard. Until then you'll see a pending page. You can still update your details in Settings while you wait.$h$, $h$If your account was not approved, the pending page will say so. Update your information and contact HILLink so we can take another look.

Athletes: sign up with your student email ending in **.edu**. Other emails can't create athlete accounts.$h$, '{}'::text[], $h$both$h$, $h$live$h$, $h$account_approval$h$, array[$h$pending$h$, $h$approval$h$, $h$approved$h$, $h$waiting$h$, $h$review$h$, $h$locked$h$, $h$rejected$h$, $h$verify$h$]::text[], array[$h$Why can't I get into my dashboard?$h$, $h$How long does approval take?$h$, $h$My account is under review$h$]::text[], array[$h$contact-hillink$h$]::text[], true, false, 10, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$change-email-or-close-account$h$, $h$account-privacy$h$, $h$How do I change my email or close my account?$h$, $h$Both are in Settings. Change your email under your account details. To close your account for good, use Terminate Account in the Danger Zone.$h$, $h$## Changing your email
Enter your new email in Settings and choose **Change email**. Follow the confirmation email that's sent to you.

## Closing your account
Choose **Terminate Account** in the Danger Zone at the bottom of Settings. You'll be asked to confirm and type TERMINATE.

- This is permanent, and your access ends right away.
- For businesses, your HILLink subscription is cancelled as part of closing the account.

Your data is handled as described in the Privacy Policy linked at the bottom of every page.$h$, '{}'::text[], $h$both$h$, $h$live$h$, $h$account_settings$h$, array[$h$email$h$, $h$delete account$h$, $h$terminate$h$, $h$close$h$, $h$cancel account$h$, $h$privacy$h$, $h$remove$h$]::text[], array[$h$How do I delete my account?$h$, $h$Can I change my login email?$h$]::text[], '{}'::text[], false, false, 10, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$disputes-and-problems$h$, $h$disputes$h$, $h$What if something goes wrong with a campaign?$h$, $h$Email HILLink with the campaign name and what happened. The HILLink team reviews disputes between athletes and businesses and decides how to resolve them.$h$, $h$Examples: an athlete didn't post, a post was rejected unfairly, or a business isn't responding.

Include:
- the campaign name
- the other person or business involved
- what you expected and what happened
- links or screenshots that show it

While a dispute is open, the athlete's proof is not approved automatically.$h$, '{}'::text[], $h$both$h$, $h$live$h$, $h$disputes$h$, array[$h$dispute$h$, $h$problem$h$, $h$unfair$h$, $h$rejected$h$, $h$scam$h$, $h$not paid$h$, $h$complaint$h$, $h$report$h$]::text[], array[$h$How do I report a problem?$h$, $h$How do I open a dispute?$h$]::text[], array[$h$contact-hillink$h$]::text[], false, true, 10, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$contact-hillink$h$, $h$contact$h$, $h$How do I contact HILLink?$h$, $h$Email contact@hillink.io. Tell us your account email, what you were trying to do, and what happened.$h$, $h$Use **Contact HILLink** at the bottom of any help article to start an email with your account type already filled in.$h$, '{}'::text[], $h$both$h$, $h$live$h$, $h$support$h$, array[$h$contact$h$, $h$support$h$, $h$email$h$, $h$help$h$, $h$talk to someone$h$, $h$customer service$h$, $h$human$h$]::text[], array[$h$How do I reach support?$h$, $h$Can I talk to a person?$h$]::text[], '{}'::text[], false, false, 10, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$athlete-start-here$h$, $h$getting-started$h$, $h$HILLink for athletes: start here$h$, $h$Set up your profile, find a campaign near you, post about the business, send proof, and get paid once the business approves.$h$, $h$## Good to know

- **Some campaigns accept you right away.** Others let the business choose, so you apply and wait. [How joining works](/help/finding-campaigns/how-to-join-a-campaign)
- **Your pay is already set aside.** The business funds your pay when it accepts you. [When do I get paid?](/help/payments/when-do-i-get-paid)
- **Good work helps you get more campaigns.** Ratings, on-time posts and customers you bring in build your [Hillink Score](/help/hillink-score/hillink-score-for-athletes).$h$, array[$h$Sign up with your .edu student email and confirm it. HILLink reviews and approves your account.$h$, $h$Finish your profile, then confirm your eligibility (age, visa status and school disclosure).$h$, $h$In Settings, connect your Stripe payout account so you can be paid.$h$, $h$Open Find Campaigns on your dashboard and choose Review & Join on a campaign you like.$h$, $h$Once you're accepted, do exactly what the campaign asks and include #ad in your post.$h$, $h$Paste the link to your live post in My Campaigns and choose Submit Proof.$h$, $h$The business approves your proof, and your pay is sent to your Stripe account. You earn XP too.$h$]::text[], $h$athlete$h$, $h$live$h$, $h$onboarding$h$, array[$h$start$h$, $h$new$h$, $h$beginner$h$, $h$how to$h$, $h$first campaign$h$, $h$getting started$h$, $h$101$h$, $h$guide$h$]::text[], array[$h$How do I get started?$h$, $h$I'm new, what do I do?$h$, $h$How does HILLink work for athletes?$h$]::text[], array[$h$how-to-join-a-campaign$h$, $h$how-to-submit-proof$h$, $h$when-do-i-get-paid$h$]::text[], true, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-campaigns-work$h$, $h$finding-campaigns$h$, $h$How do campaigns work?$h$, $h$A campaign is a paid (or in-kind) job from a local business. You join, create the post it asks for, send proof, and get paid when the business approves.$h$, $h$Open **Find Campaigns** on your dashboard to see the marketplace. Each campaign shows:

- what to post and how many posts
- the pay per athlete, and anything extra (like a free meal)
- which athlete tiers can join
- how many spots are left
- the business, its location, and the due date

Use the filters to narrow by deal type, tier, pay, state or distance. To use distance, add your city and state in Settings.

Tap a business name to see the full campaign, then choose **Review & Join**.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$campaign_marketplace$h$, array[$h$campaign$h$, $h$marketplace$h$, $h$find$h$, $h$browse$h$, $h$deals$h$, $h$jobs$h$, $h$gigs$h$, $h$filter$h$]::text[], array[$h$Where do I find campaigns?$h$, $h$How do I find deals near me?$h$]::text[], array[$h$how-to-join-a-campaign$h$, $h$campaign-types$h$, $h$why-cant-i-join-a-campaign$h$]::text[], true, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-to-join-a-campaign$h$, $h$finding-campaigns$h$, $h$How do I join a campaign?$h$, $h$Choose Review & Join. On first-come campaigns you're accepted right away if you qualify. On campaigns where the business selects, you apply and the business accepts or declines you.$h$, $h$## First come, first served
If you qualify and a spot is open, you're accepted instantly. These campaigns can also require you to be within a set distance of the business, so make sure your city and state are in your profile. They stop taking new athletes 12 hours before the campaign starts.

## Business selects
You apply, and the business reviews your profile. You'll get a notification when you're accepted or not selected.

## After you're accepted
The campaign moves to **My Campaigns**. The business funds your pay, and you can start working. You can also get a [customer code](/help/customer-codes/customer-codes-for-athletes) to share.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$campaign_join$h$, array[$h$join$h$, $h$apply$h$, $h$accept$h$, $h$claim$h$, $h$sign up for campaign$h$, $h$first come$h$, $h$auto accept$h$]::text[], array[$h$How do I apply to a campaign?$h$, $h$Did I get accepted?$h$, $h$What does auto-accept mean?$h$]::text[], array[$h$why-cant-i-join-a-campaign$h$, $h$campaign-requirements-explained$h$]::text[], true, false, 2, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$why-cant-i-join-a-campaign$h$, $h$finding-campaigns$h$, $h$Why can't I join a campaign?$h$, $h$The message on the campaign tells you why. The most common reasons are unconfirmed eligibility, a full campaign, a tier requirement, or being too far away.$h$, $h$## Common reasons

- **Eligibility not confirmed.** Confirm your age, visa status and school disclosure first. [Eligibility rules](/help/account-eligibility/eligibility-requirements)
- **The campaign is full**, or it's no longer taking athletes.
- **Your tier is too low.** You'll see "not eligible for this payout yet." [How tiers work](/help/xp-levels/xp-and-tiers)
- **You're outside the campaign's distance limit**, or your profile is missing your location.
- **Too close to the start.** First-come campaigns close 12 hours before they start.
- **Your school has an exclusive sponsor** in this business's category.
- **The business is in a category athletes can't promote.**
- **Your student visa** status doesn't allow paid NIL work.
- **Your rating is below 1.5 stars.** You can't apply until it improves.
- **You already applied** to this campaign.

If none of these fit, contact HILLink with the campaign name.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$campaign_eligibility$h$, array[$h$can't join$h$, $h$cannot apply$h$, $h$not eligible$h$, $h$blocked$h$, $h$full$h$, $h$radius$h$, $h$tier$h$, $h$error$h$]::text[], array[$h$Why am I not eligible?$h$, $h$It says not eligible for this payout yet$h$, $h$Why is the campaign unavailable?$h$]::text[], array[$h$eligibility-requirements$h$, $h$xp-and-tiers$h$, $h$contact-hillink$h$]::text[], false, false, 3, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$campaign-requirements-explained$h$, $h$campaign-requirements$h$, $h$What are campaign requirements?$h$, $h$Requirements are the business's instructions: what to post, the format, how many posts, the deadline, and the proof you need to send. Follow them exactly to get approved.$h$, $h$Open the campaign from **My Campaigns** or the marketplace to see:

- **Directions**: what to say or show, tags or mentions, and the call to action.
- **Content format**: feed post, story, reel, carousel or video.
- **Number of posts.**
- **Deadline**: how many days you have to post after you're accepted.
- **Proof checklist**: what the business will check, such as a live post link and the #ad label.

Every campaign requires #ad or Instagram's Paid partnership label. [Why #ad is required](/help/safety-rules/ad-disclosure-rules)$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$campaign_requirements$h$, array[$h$requirements$h$, $h$deliverables$h$, $h$directions$h$, $h$instructions$h$, $h$deadline$h$, $h$what do i post$h$, $h$checklist$h$]::text[], array[$h$What do I have to post?$h$, $h$How long do I have to post?$h$]::text[], array[$h$how-to-submit-proof$h$, $h$ad-disclosure-rules$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-to-submit-proof$h$, $h$proof-approval$h$, $h$How do I submit proof?$h$, $h$In My Campaigns, paste the link to your live post in the Proof URL box, add any notes, and choose Submit Proof.$h$, $h$You can submit proof once the business has accepted you. Double-check your link before you submit.

There's no screenshot upload. The business checks your live post through the link, so make sure it's public and shows everything the campaign asks for, including #ad.

If the business asks for changes, fix your post, paste the new link, and choose **Submit Again**.

If you post on Instagram and your account is connected, HILLink also pulls your post's stats (likes, comments, reach). Use **Sync Diagnostics** to refresh them.$h$, array[$h$Publish your post, including #ad or the Paid partnership label.$h$, $h$Copy the link to the live post.$h$, $h$Open My Campaigns on your dashboard and find the campaign.$h$, $h$Paste the link in Proof URL and add notes if helpful.$h$, $h$Choose Submit Proof.$h$]::text[], $h$athlete$h$, $h$live$h$, $h$proof_submission$h$, array[$h$proof$h$, $h$submit$h$, $h$link$h$, $h$url$h$, $h$upload$h$, $h$post link$h$, $h$screenshot$h$]::text[], array[$h$Where do I upload my post?$h$, $h$How do I show I posted?$h$, $h$How do I send my post link?$h$]::text[], array[$h$what-happens-after-i-submit-proof$h$, $h$campaign-requirements-explained$h$]::text[], true, false, 1, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$what-happens-after-i-submit-proof$h$, $h$proof-approval$h$, $h$What happens after I submit proof?$h$, $h$The business reviews your proof. If they approve it, you're paid and earn XP. If they don't review it within the campaign's review window (72 hours by default), it's approved automatically once your pay is funded.$h$, $h$## If the business approves
You get a notification, your pay is sent to your Stripe account, and you earn XP for completing the campaign. [When do I get paid?](/help/payments/when-do-i-get-paid)

## If the business doesn't respond
Proof that waits longer than the campaign's review window is approved automatically. The window is 72 hours by default and never shorter than 24 hours. This only happens once the business has funded your pay, and not while a dispute is open.

## If the business asks for changes
You'll get a notification and the campaign shows **Needs changes** in My Campaigns. Check the campaign requirements, fix your post, then paste the new link and choose **Submit Again**. The business reviews it again, with a new review window. If you think the decision is wrong, [contact HILLink](/help/disputes/disputes-and-problems).

After approval, the business may also [rate your work](/help/ratings/how-athlete-ratings-work).$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$proof_review$h$, array[$h$approval$h$, $h$approved$h$, $h$rejected$h$, $h$review$h$, $h$waiting$h$, $h$auto approve$h$, $h$72 hours$h$, $h$pending proof$h$, $h$resubmit$h$, $h$needs changes$h$, $h$fix$h$]::text[], array[$h$How long does approval take?$h$, $h$Why hasn't my proof been approved?$h$, $h$My proof was rejected$h$, $h$Can I resubmit my proof?$h$]::text[], array[$h$when-do-i-get-paid$h$, $h$how-athlete-ratings-work$h$, $h$disputes-and-problems$h$]::text[], true, false, 2, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$dropping-a-campaign$h$, $h$completing-campaigns$h$, $h$Can I drop a campaign after joining?$h$, $h$Yes. Choose Drop Campaign in My Campaigns any time before your proof is approved. Your spot opens up again and the business gets back the money it set aside for you.$h$, $h$Only drop a campaign if you really can't do it. Finishing campaigns you join, on time, is part of your [Hillink Score](/help/hillink-score/hillink-score-for-athletes).$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$withdraw_application$h$, array[$h$drop$h$, $h$withdraw$h$, $h$leave$h$, $h$quit$h$, $h$cancel$h$, $h$can't do it$h$]::text[], array[$h$How do I cancel a campaign?$h$, $h$How do I withdraw my application?$h$]::text[], '{}'::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$set-up-payouts$h$, $h$payments$h$, $h$How do I set up payouts?$h$, $h$Go to Settings and choose Connect Stripe Payout Account. HILLink pays athletes through Stripe, so you need a connected Stripe account before any pay can be sent.$h$, $h$Stripe handles your bank details. HILLink never sees your full bank account number.

If a campaign is approved before your payout account is ready, your pay stays held for you. After you finish setup, the business can send it from their dashboard. Contact HILLink if it doesn't arrive.$h$, array[$h$Open Settings from your dashboard.$h$, $h$Under Payout Receiving Information, choose Connect Stripe Payout Account.$h$, $h$Finish Stripe's setup (your details and a bank account or debit card).$h$, $h$Come back to HILLink. Once Stripe confirms your account, you're ready to be paid.$h$]::text[], $h$athlete$h$, $h$live$h$, $h$payouts$h$, array[$h$payout$h$, $h$stripe$h$, $h$bank$h$, $h$connect$h$, $h$direct deposit$h$, $h$set up payment$h$, $h$get paid$h$]::text[], array[$h$How do I add my bank account?$h$, $h$How do I connect Stripe?$h$]::text[], array[$h$when-do-i-get-paid$h$]::text[], true, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$when-do-i-get-paid$h$, $h$payments$h$, $h$When do I get paid?$h$, $h$Your pay is sent to your Stripe account as soon as the business approves your proof. Stripe then moves it to your bank on its normal payout schedule.$h$, $h$## How your pay is protected
When a business accepts you, it pays HILLink your campaign pay up front. That money is held for you. When your proof is approved, it's sent to you. You get the full pay listed on the campaign; HILLink's fee is charged to the business, not taken out of your pay.

## What has to be true to get paid
- Your proof is approved (by the business, or automatically after the review window).
- Your [Stripe payout account](/help/payments/set-up-payouts) is connected.

## Checking your payments
Your earnings page lists each campaign payment and when it was paid: [My Earnings](/athlete/earnings).

## In-kind campaigns
Some campaigns pay with something other than money, like a free meal or product. Those have no cash payout.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$payouts$h$, array[$h$paid$h$, $h$payment$h$, $h$payout$h$, $h$money$h$, $h$when$h$, $h$how long$h$, $h$stripe$h$, $h$earnings$h$, $h$bank$h$]::text[], array[$h$How do payouts work?$h$, $h$Where is my money?$h$, $h$How long until I get paid?$h$, $h$Why haven't I been paid?$h$]::text[], array[$h$set-up-payouts$h$, $h$what-happens-after-i-submit-proof$h$]::text[], true, true, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-athlete-ratings-work$h$, $h$ratings$h$, $h$How do athlete ratings work?$h$, $h$After approving your work, a business can rate you from 1 to 5 stars and leave a short review. Your average rating shows on your dashboard.$h$, $h$- Each campaign can be rated once.
- Your average is the average of all your ratings.
- Ratings are the biggest part of your [Hillink Score](/help/hillink-score/hillink-score-for-athletes).
- If your average falls below **1.5 stars**, you can't apply to new campaigns until it improves.

The best way to earn strong ratings: follow the campaign directions exactly, post on time, and include #ad.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$ratings$h$, array[$h$rating$h$, $h$stars$h$, $h$review$h$, $h$feedback$h$, $h$average$h$, $h$1.5$h$]::text[], array[$h$What are ratings?$h$, $h$How do I improve my rating?$h$, $h$Who rates me?$h$]::text[], array[$h$hillink-score-for-athletes$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$xp-and-tiers$h$, $h$xp-levels$h$, $h$What are XP and athlete tiers?$h$, $h$You earn XP for campaign work. Your total XP sets your tier: Bronze, Silver, Gold, Platinum or Diamond. Some campaigns are only open to higher tiers.$h$, $h$## Tiers
- Bronze: 0 XP
- Silver: 1,000 XP
- Gold: 2,500 XP
- Platinum: 5,000 XP
- Diamond: 8,000 XP

## How you earn XP
- Accepted into a campaign: 25 XP
- Proof submitted: 20 XP
- Proof approved: 160 XP (120 for completing the campaign plus 40 for the approved post)
- Proof sent by the campaign's due date: 30 XP bonus
- XP Challenges on your dashboard, like Campaign Starter and Closer
- A bonus when a connected Instagram post performs very well

Your dashboard shows your XP, your tier and how much XP you need for the next tier.

## Tiers and seasonal levels are different
Your **tier** is based on all the XP you've ever earned. The [rewards road](/help/rewards/rewards-road) has separate **levels 1–50** that restart every semester.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$xp$h$, array[$h$xp$h$, $h$experience$h$, $h$tier$h$, $h$level$h$, $h$bronze$h$, $h$silver$h$, $h$gold$h$, $h$platinum$h$, $h$diamond$h$, $h$rank$h$]::text[], array[$h$What is Gold level?$h$, $h$How do I level up?$h$, $h$How are levels calculated?$h$, $h$How do I get to the next tier?$h$]::text[], array[$h$rewards-road$h$, $h$why-cant-i-join-a-campaign$h$]::text[], true, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$hillink-score-for-athletes$h$, $h$hillink-score$h$, $h$What is my Hillink Score?$h$, $h$Your Hillink Score is a number from 0 to 100 that shows businesses how reliable you are. It's built from your ratings, posting on time, getting approved the first time, and customers you bring in.$h$, $h$## What goes into it
- **Star ratings from businesses**: 40%
- **Proof sent on time**: 25%
- **Proof approved the first time**: 15%
- **Customers who use your code, per campaign**: 20%

New athletes start near the middle and are marked **New** until they finish 3 campaigns, so one campaign can't swing your score too far.

Your score is updated daily. Your dashboard shows it, each part, and one tip to raise it. Businesses see it on your athlete card.

A score of 90 or more after 3 campaigns unlocks the Pro track on the [rewards road](/help/rewards/rewards-road).$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$hillink_score$h$, array[$h$score$h$, $h$hillink score$h$, $h$credit score$h$, $h$reliability$h$, $h$rating$h$, $h$pro$h$]::text[], array[$h$How is my score calculated?$h$, $h$How do I raise my Hillink Score?$h$]::text[], array[$h$how-athlete-ratings-work$h$, $h$customer-codes-for-athletes$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$rewards-road$h$, $h$rewards$h$, $h$How does the rewards road work?$h$, $h$Each semester you climb levels 1 to 50 with the XP you earn, collect points for levels, badges and customers you bring in, and unlock badges. Open it from your dashboard.$h$, $h$## Seasons
Seasons follow the school year: spring (January to May), summer (June and July) and fall (August to December). Levels and points start over each season. Your tier, XP and Hillink Score carry over.

## Levels
Level 2 takes 60 XP, and each level after that takes a little more.

## Points
- Every level: 10 points
- Every 5th level: 25 bonus points
- Each customer who uses your code: 5 points (up to 20 customers per campaign each season)
- Each badge, the first time you earn it: 20 points

## Pro track
Reach a Hillink Score of 90 or more after 3 campaigns to unlock the Pro track: 15 extra points every level and 50 extra every 5th level. You never pay for Pro.

## Badges
First Campaign, Regular (5 campaigns), 10 Customers Driven, 5-Star Streak, Always On Time, Verified Reach, and Hillink Pro.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$rewards_road$h$, array[$h$rewards$h$, $h$points$h$, $h$badges$h$, $h$season$h$, $h$semester$h$, $h$levels$h$, $h$battle pass$h$, $h$pro track$h$]::text[], array[$h$How do I earn points?$h$, $h$What are badges?$h$, $h$What is the Pro track?$h$]::text[], array[$h$xp-and-tiers$h$, $h$hillink-score-for-athletes$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$rewards-store$h$, $h$rewards$h$, $h$Spending points in the rewards store$h$, $h$Planned: athletes will spend rewards-road points on HILLink merch and partner rewards.$h$, $h$Internal note: store items exist in the database with active = false until point values and item prices are decided. Keep this article in planned status until at least one item is turned on.$h$, '{}'::text[], $h$athlete$h$, $h$planned$h$, $h$rewards_store$h$, array[$h$store$h$, $h$merch$h$, $h$redeem$h$, $h$spend points$h$, $h$hoodie$h$, $h$shirt$h$]::text[], '{}'::text[], '{}'::text[], false, false, 50, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$customer-codes-for-athletes$h$, $h$customer-codes$h$, $h$How do customer codes work for athletes?$h$, $h$Once you're accepted into a campaign, choose Get customer code. Share the code or its link in your post. Every customer who shows it at the business counts toward your results.$h$, $h$Your code looks like **JAKE-7K2Q**. The link shows customers the business, any offer it gives for using the code, and your code.

- Codes only work at the business running the campaign.
- A code stops working if you leave the campaign.
- Each customer earns you 5 rewards points, up to 20 customers per campaign each season.
- Customers you bring in also count toward your [Hillink Score](/help/hillink-score/hillink-score-for-athletes).$h$, array[$h$Open My Campaigns and choose Get customer code on the campaign.$h$, $h$Put the code in your post or story, or share the link that comes with it.$h$, $h$Customers show the code at the business, and the business records it.$h$]::text[], $h$athlete$h$, $h$live$h$, $h$customer_codes$h$, array[$h$customer code$h$, $h$promo code$h$, $h$discount code$h$, $h$share link$h$, $h$redemption$h$, $h$customers$h$]::text[], array[$h$What is a customer code?$h$, $h$Where do I get my promo code?$h$]::text[], array[$h$rewards-road$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$eligibility-requirements$h$, $h$account-eligibility$h$, $h$What do I need to be eligible?$h$, $h$You must be 18 or older, tell HILLink your visa status, agree to report HILLink deals to your school, and list any categories where your school has an exclusive sponsor.$h$, $h$Confirm these on your eligibility page. Until you do, your dashboard shows a reminder and you can't join campaigns.

- **Age**: you must be 18 or older.
- **Visa**: student visas usually don't allow paid NIL work in the US. If you're an international student who hasn't been cleared by your school, you can't join campaigns.
- **School disclosure**: you agree to report your HILLink deals to your school.
- **School sponsors**: if your school has an exclusive deal in a category (for example, apparel or drinks), you won't be able to join campaigns from businesses in that category.

Update your answers any time on the [eligibility page](/athlete/eligibility).$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$compliance$h$, array[$h$eligible$h$, $h$eligibility$h$, $h$age$h$, $h$18$h$, $h$visa$h$, $h$international$h$, $h$school$h$, $h$confirm$h$]::text[], array[$h$Why do I need to confirm eligibility?$h$, $h$Can international students use HILLink?$h$]::text[], array[$h$nil-school-rules$h$, $h$why-cant-i-join-a-campaign$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$nil-school-rules$h$, $h$nil-compliance$h$, $h$NIL and school rules on HILLink$h$, $h$HILLink blocks campaigns that would break common NIL rules, but you're still responsible for following your school's policies and reporting your deals.$h$, $h$## Categories athletes can't promote
HILLink doesn't allow businesses in these categories, and athletes can't join their campaigns:
- bars, breweries and liquor stores
- tobacco and vape
- cannabis, CBD and hemp
- betting, casinos and sweepstakes
- adult entertainment
- firearms and weapons
- supplements and weight loss (they can contain NCAA-banned substances)

## Your school's rules
Your school may have its own rules, including exclusive sponsors. Tell HILLink about exclusive categories on your eligibility page so those campaigns are blocked for you.

HILLink doesn't give legal or compliance advice. When in doubt, ask your school's compliance office before joining a campaign.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$compliance$h$, array[$h$nil$h$, $h$ncaa$h$, $h$compliance$h$, $h$school$h$, $h$rules$h$, $h$alcohol$h$, $h$betting$h$, $h$supplements$h$, $h$banned$h$, $h$restricted$h$]::text[], array[$h$Is HILLink NCAA compliant?$h$, $h$Do I have to tell my school?$h$]::text[], array[$h$eligibility-requirements$h$, $h$ad-disclosure-rules$h$]::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$ad-disclosure-rules$h$, $h$safety-rules$h$, $h$Why do I have to use #ad?$h$, $h$US advertising rules (from the FTC) require paid posts to be clearly labeled. Every HILLink campaign post must include #ad or use Instagram's Paid partnership label.$h$, $h$- Put **#ad** where people will see it, or turn on Instagram's **Paid partnership** label.
- Make sure it shows in your proof, because businesses check for it.
- Follow the campaign's directions, and only say things about the business that are true.$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$ftc_disclosure$h$, array[$h$#ad$h$, $h$ad$h$, $h$ftc$h$, $h$disclosure$h$, $h$paid partnership$h$, $h$sponsored$h$, $h$label$h$]::text[], array[$h$Do I need to say it's an ad?$h$, $h$What is the Paid partnership label?$h$]::text[], '{}'::text[], false, false, 1, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$business-start-here$h$, $h$getting-started$h$, $h$HILLink for businesses: start here$h$, $h$Choose a plan, post a campaign, accept athletes and fund their pay, then approve their posts. Athletes are paid automatically when you approve.$h$, $h$## Good to know

- **You don't have to watch every post.** Proof you don't review within 72 hours is approved automatically, as long as you've funded it. [Reviewing proof](/help/proof-approval/how-to-review-proof)
- **You only pay for athletes you accept.** Money is held and only released when work is approved. [Paying athletes](/help/payments/paying-athletes)
- **See your results.** Customer codes show how many customers each athlete brought in. [Customer codes](/help/customer-codes/customer-codes-for-businesses)$h$, array[$h$Create your account and business profile. HILLink reviews and approves new businesses.$h$, $h$In Settings, choose a plan and finish billing. You need an active plan to post campaigns.$h$, $h$Choose Post New Campaign. Pick a campaign type, what athletes should post, pay per athlete, and how many athletes.$h$, $h$Athletes join. On first-come campaigns they're accepted automatically; otherwise you accept the ones you want.$h$, $h$Fund each accepted athlete's pay through Stripe. The money is held until you approve their work.$h$, $h$When an athlete submits proof, open it, then Approve or Reject. Approving pays the athlete.$h$, $h$Track customers who used athletes' codes under Results & customer codes.$h$]::text[], $h$business$h$, $h$live$h$, $h$onboarding$h$, array[$h$start$h$, $h$new$h$, $h$beginner$h$, $h$how to$h$, $h$first campaign$h$, $h$getting started$h$, $h$101$h$, $h$guide$h$, $h$setup$h$]::text[], array[$h$How do I get started?$h$, $h$How does HILLink work for businesses?$h$, $h$What do I do first?$h$]::text[], array[$h$business-plans$h$, $h$how-to-create-a-campaign$h$, $h$paying-athletes$h$]::text[], true, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-to-create-a-campaign$h$, $h$creating-campaigns$h$, $h$How do I create a campaign?$h$, $h$Choose Post New Campaign on your dashboard, fill in what you want athletes to do and what you'll pay, then choose Create Campaign.$h$, $h$## Tips
- **Directions** are what athletes follow. Include what to say, tags or mentions, and your call to action.
- **Customer offer** (optional) is what customers get for using an athlete's code, such as 10% off.
- **Additional compensation** (optional) is anything extra, like a free meal.
- **Saved templates** let you reuse a campaign setup.

## Limits from your plan
Your plan sets how many campaigns can be open at once, how many athletes each campaign can have, and the highest athlete tier you can choose. [Business plans](/help/plans-billing/business-plans)$h$, array[$h$Make sure your plan is active in Settings.$h$, $h$Choose Post New Campaign.$h$, $h$Pick a campaign type and content format.$h$, $h$Add a title, a short description and your goal (for example, bringing in customers).$h$, $h$Set the number of posts, the posting deadline and how athletes join.$h$, $h$Choose which athlete tiers can join, the number of athletes and the pay per athlete.$h$, $h$Add clear directions and choose the proof you want.$h$, $h$Review the summary, confirm the two checkboxes, and choose Create Campaign.$h$]::text[], $h$business$h$, $h$live$h$, $h$campaign_builder$h$, array[$h$create$h$, $h$post$h$, $h$new campaign$h$, $h$campaign builder$h$, $h$launch$h$, $h$set up campaign$h$, $h$template$h$]::text[], array[$h$How do I post a campaign?$h$, $h$How do I make a new campaign?$h$]::text[], array[$h$campaign-types$h$, $h$choosing-proof-requirements$h$, $h$how-athletes-join-your-campaign$h$]::text[], true, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$how-athletes-join-your-campaign$h$, $h$choosing-athletes$h$, $h$How do athletes join my campaign?$h$, $h$You choose when you create the campaign. With first come, first served, qualifying athletes are accepted automatically. With business selects, athletes apply and you accept or decline them.$h$, $h$## First come, first served
Athletes who qualify are accepted instantly until your spots are full. You'll get a notification each time. Athletes must be within the campaign's distance limit, and new athletes can't join in the last 12 hours before the campaign starts.

## Business selects
Athletes apply and you get a notification. Open the campaign, view the athlete's full profile, and choose **Accept** or **Decline**. Monthly Ambassador campaigns always use this option.

## After you accept
You'll be asked to fund the athlete's pay. [Paying athletes](/help/payments/paying-athletes)

## Finding athletes yourself
Use **Find Athletes** on your dashboard to browse athletes, including their tier, rating and Hillink Score.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_join$h$, array[$h$athletes join$h$, $h$accept$h$, $h$decline$h$, $h$applicants$h$, $h$auto accept$h$, $h$first come$h$, $h$choose athletes$h$, $h$select$h$]::text[], array[$h$How do I pick athletes?$h$, $h$Who can join my campaign?$h$, $h$What is auto-accept?$h$]::text[], array[$h$paying-athletes$h$, $h$athlete-tiers-for-businesses$h$]::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$choosing-proof-requirements$h$, $h$campaign-requirements$h$, $h$What should I ask athletes to submit as proof?$h$, $h$Each campaign type comes with a proof checklist, such as a live post link and a post that says #ad. Athletes send proof as a link to their live post, so ask for things you can check by opening that link.$h$, $h$Examples from the built-in checklists:
- live post link
- post includes the required tags or mentions
- post says #ad or uses the Paid partnership label (always included, because the FTC requires it)
- post shows the visit (Dine and Post) or the product (Product Review)

Athletes send proof by pasting a link to their live post and adding notes. There's no screenshot upload. For campaigns with several posts, athletes put the extra links in the notes.

Clear directions get better posts. Say exactly what to mention, what to show and what customers should do.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_requirements$h$, array[$h$proof$h$, $h$requirements$h$, $h$checklist$h$, $h$deliverables$h$, $h$what to ask$h$, $h$directions$h$]::text[], array[$h$What proof should I require?$h$, $h$How do I write good directions?$h$]::text[], array[$h$how-to-review-proof$h$, $h$how-to-create-a-campaign$h$]::text[], false, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$how-to-review-proof$h$, $h$proof-approval$h$, $h$How do I review campaign proof?$h$, $h$When an athlete submits proof, open the campaign on your dashboard, choose View Proof, then Approve or Reject. Approving pays the athlete from the money you funded.$h$, $h$## Before you can approve
The athlete's pay must be funded. If it isn't, you'll see **Fund payment** first.

## If you don't review it
Proof you don't review within the campaign's review window (72 hours by default) is approved automatically and the athlete is paid. This only happens for funded work and never while a dispute is open. Unfunded work is never auto-approved; you'll get a reminder instead.

## Rejecting
Reject proof that doesn't meet your requirements. The athlete is notified and can fix their post and send it again. Their funded pay stays held until you approve, and the review window starts over when they resubmit. If you're not sure, [contact HILLink](/help/disputes/disputes-and-problems).

## After approving
You're asked to rate the athlete right away. You can also rate them later with **Rate Athlete**. [Rating athletes](/help/ratings/rating-athletes)

## Post stats
For Instagram posts, **Sync Diagnostics** shows likes, comments and reach when the athlete's account is connected.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$proof_review$h$, array[$h$review$h$, $h$approve$h$, $h$reject$h$, $h$proof$h$, $h$view proof$h$, $h$auto approve$h$, $h$72 hours$h$, $h$submission$h$, $h$resubmit$h$]::text[], array[$h$How do I approve a post?$h$, $h$What happens if I don't review proof?$h$]::text[], array[$h$paying-athletes$h$, $h$rating-athletes$h$, $h$after-an-athlete-is-approved$h$]::text[], true, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$after-an-athlete-is-approved$h$, $h$proof-approval$h$, $h$What happens when an athlete's work is approved?$h$, $h$The athlete is paid from the money you funded, earns XP, and their part of the campaign shows as completed. You can then rate them and track customers they bring in.$h$, $h$- **Payment**: the athlete's pay is sent to their Stripe account. If their payout account isn't set up yet, a **Pay athlete** button lets you send it later.
- **Ratings**: you're asked to rate the athlete from 1 to 5 stars as soon as you approve. [Rating athletes](/help/ratings/rating-athletes)
- **Results**: customers who use the athlete's code keep counting in your [monthly results](/help/results/monthly-results-report).$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_completion$h$, array[$h$completed$h$, $h$complete$h$, $h$done$h$, $h$finished$h$, $h$after approval$h$, $h$campaign completed$h$]::text[], array[$h$What happens when a campaign is completed?$h$, $h$What do I do after approving?$h$]::text[], array[$h$rating-athletes$h$, $h$monthly-results-report$h$]::text[], false, false, 1, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$rating-athletes$h$, $h$ratings$h$, $h$How do athlete ratings work?$h$, $h$After an athlete's work is approved, you can rate them from 1 to 5 stars and add a short review. Ratings help other businesses and shape the athlete's Hillink Score.$h$, $h$- When you approve an athlete's work, a rating window opens right away.
- To rate later, open the campaign on your dashboard (or in **Campaign History**), expand the athlete, and choose **Rate Athlete**.
- You can rate each athlete once per campaign.
- An athlete's average rating shows on their profile.
- Athletes whose average falls below 1.5 stars can't apply to new campaigns.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$ratings$h$, array[$h$rate$h$, $h$rating$h$, $h$stars$h$, $h$review athlete$h$, $h$feedback$h$]::text[], array[$h$How do I rate an athlete?$h$, $h$Where is the Rate Athlete button?$h$]::text[], array[$h$hillink-score-for-businesses$h$]::text[], false, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$athlete-tiers-for-businesses$h$, $h$xp-levels$h$, $h$What do athlete tiers mean?$h$, $h$Athletes move up from Bronze to Silver, Gold, Platinum and Diamond as they earn XP by completing campaigns. Higher tiers mean more completed, approved work on HILLink.$h$, $h$## Tiers
- Bronze: new athletes
- Silver: 1,000 XP
- Gold: 2,500 XP
- Platinum: 5,000 XP
- Diamond: 8,000 XP

Athletes earn most of their XP from accepted and approved campaigns.

## Using tiers in your campaigns
When you create a campaign, you choose which tiers can join. Your plan sets the highest tier you can choose. [Business plans](/help/plans-billing/business-plans)

For a fuller picture of an athlete, look at their [Hillink Score](/help/hillink-score/hillink-score-for-businesses) and rating.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$xp$h$, array[$h$tier$h$, $h$level$h$, $h$bronze$h$, $h$silver$h$, $h$gold$h$, $h$platinum$h$, $h$diamond$h$, $h$xp$h$, $h$athlete level$h$]::text[], array[$h$What is a Gold athlete?$h$, $h$What do athlete levels mean?$h$]::text[], array[$h$hillink-score-for-businesses$h$, $h$business-plans$h$]::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$hillink-score-for-businesses$h$, $h$hillink-score$h$, $h$What is the Hillink Score?$h$, $h$A 0 to 100 score on each athlete's card that shows how reliable they are, based on ratings, on-time posts, approvals on the first try, and customers they bring in.$h$, $h$- Star ratings from businesses: 40%
- Proof sent on time: 25%
- Proof approved the first time: 15%
- Customers per campaign: 20%

Athletes with fewer than 3 finished campaigns are marked **New**. In **Find Athletes**, sort by **Best Hillink Score** to see the most reliable athletes first. Follower counts marked ✓ are verified from the athlete's connected Instagram.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$hillink_score$h$, array[$h$score$h$, $h$hillink score$h$, $h$reliability$h$, $h$best athletes$h$, $h$verified followers$h$]::text[], array[$h$How do I find reliable athletes?$h$, $h$What does the score on athlete cards mean?$h$]::text[], array[$h$athlete-tiers-for-businesses$h$, $h$rating-athletes$h$]::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$business-plans$h$, $h$plans-billing$h$, $h$How do business plans work?$h$, $h$HILLink has four monthly plans. Your plan sets how many campaigns you can run at once, how many athletes each campaign can have, and the highest athlete tier you can work with.$h$, $h$## Plans
- **Starter**, $250/month: 2 open campaigns, up to 3 athletes each, athletes up to Silver
- **Growth**, $400/month: 5 open campaigns, up to 6 athletes each, athletes up to Gold
- **Scale**, $700/month: 10 open campaigns, up to 12 athletes each, athletes up to Platinum
- **Domination**, $1,200/month: 20 open campaigns, up to 20 athletes each, all tiers including Diamond

Choose your plan and billing details in **Settings**, then pay through Stripe's secure checkout. You need an active plan before you can post a campaign.

## Changing or cancelling your plan
- **Switch plans:** in Settings, pick a new tier and choose **Pay and Activate Tier**. Stripe charges or credits the difference right away.
- **Cancel, update your card or see invoices:** choose **Manage billing or cancel plan** in Settings. Without an active plan you can't post new campaigns.

## Athlete pay
Athlete pay isn't included in your plan. For each athlete you accept, you pay their campaign pay plus HILLink's 20% platform fee and card processing. [Paying athletes](/help/payments/paying-athletes)$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$subscriptions$h$, array[$h$plan$h$, $h$pricing$h$, $h$price$h$, $h$subscription$h$, $h$billing$h$, $h$starter$h$, $h$growth$h$, $h$scale$h$, $h$domination$h$, $h$cost$h$, $h$cancel$h$, $h$upgrade$h$, $h$downgrade$h$, $h$invoice$h$, $h$card$h$]::text[], array[$h$How much does HILLink cost?$h$, $h$What plan do I need?$h$, $h$How do I pay for HILLink?$h$, $h$How do I cancel my plan?$h$, $h$How do I change my plan?$h$]::text[], array[$h$paying-athletes$h$, $h$how-to-create-a-campaign$h$]::text[], true, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$paying-athletes$h$, $h$payments$h$, $h$How do athlete payments work?$h$, $h$When you accept an athlete, you fund their pay plus HILLink's 20% platform fee through Stripe. HILLink holds the money and sends the athlete's pay to them when you approve their work. If the athlete leaves or you remove them first, you're refunded.$h$, $h$## Funding
After you accept an athlete, choose **Fund payment**. The button shows the exact total before you pay. It covers:
- the athlete's pay (the athlete receives all of it)
- HILLink's platform fee: 20% of the athlete's pay
- card processing

For example, for a $100 athlete, you pay $100 plus a $20 fee, plus card processing. This is separate from your monthly plan.

## Paying out
When you approve the athlete's proof, their pay is sent to them automatically. If their payout account isn't ready yet, use **Pay athlete** later.

## Refunds
- If you remove an accepted athlete, or the athlete drops the campaign before approval, the money you funded is refunded.
- Money that has already been paid out to an athlete is not refunded.

## In-kind campaigns
If a campaign pays $0 (for example, a free meal), there's nothing to fund.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_payments$h$, array[$h$pay athletes$h$, $h$fund$h$, $h$funding$h$, $h$payment$h$, $h$refund$h$, $h$held$h$, $h$stripe$h$, $h$checkout$h$, $h$fee$h$, $h$platform fee$h$, $h$20%$h$, $h$commission$h$]::text[], array[$h$When do I pay athletes?$h$, $h$Do I get a refund if an athlete doesn't post?$h$, $h$What is Fund payment?$h$, $h$How much is HILLink's fee?$h$]::text[], array[$h$how-to-review-proof$h$, $h$removing-an-athlete$h$]::text[], true, true, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$cancelling-a-campaign$h$, $h$campaign-problems$h$, $h$Can I cancel a campaign?$h$, $h$Yes, as long as no athlete's work on it has been approved yet. Choose Cancel Campaign on your dashboard. Any athlete pay you funded is refunded and the athletes are notified.$h$, $h$- Cancelling removes the campaign and everyone who applied or joined it.
- Athletes who applied, were accepted or had sent proof get a notification.
- Money you funded for athletes is refunded to you through Stripe.
- Once any athlete's work on the campaign has been approved, it can't be cancelled.

To stop working with just one athlete, [remove them](/help/campaign-problems/removing-an-athlete) instead.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$cancel_campaign$h$, array[$h$cancel$h$, $h$delete campaign$h$, $h$stop campaign$h$, $h$end campaign$h$, $h$remove campaign$h$, $h$refund$h$]::text[], array[$h$How do I cancel a campaign?$h$, $h$How do I delete a campaign?$h$, $h$Can I stop my campaign?$h$]::text[], array[$h$removing-an-athlete$h$, $h$paying-athletes$h$]::text[], false, false, 1, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$removing-an-athlete$h$, $h$campaign-problems$h$, $h$Can I remove an athlete from my campaign?$h$, $h$Yes, any time before you approve their work. Choose Remove Athlete (or Remove Applicant) on the campaign. If you funded their pay, it's refunded.$h$, $h$- Removing an applicant declines them.
- Removing an accepted athlete takes them off the campaign and refunds their funded pay.
- You can't remove an athlete whose work you've already approved.

If an athlete didn't follow the campaign or you think something is wrong, [contact HILLink](/help/disputes/disputes-and-problems).$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$remove_athlete$h$, array[$h$remove$h$, $h$kick$h$, $h$athlete didn't post$h$, $h$no show$h$, $h$refund$h$, $h$replace athlete$h$]::text[], array[$h$An athlete didn't post, what do I do?$h$, $h$How do I remove an athlete?$h$]::text[], array[$h$paying-athletes$h$, $h$disputes-and-problems$h$]::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$customer-codes-for-businesses$h$, $h$customer-codes$h$, $h$How do customer codes work for businesses?$h$, $h$Each athlete in your campaign can share their own customer code. When a customer shows one, you or your staff log it, and it counts in your monthly results.$h$, $h$- Codes look like **JAKE-7K2Q** and only work at your business.
- The same code logged twice within 60 seconds counts once.
- A code stops working if the athlete leaves the campaign.
- Making a new staff link turns the old one off.
- Add a **customer offer** when you create a campaign (for example, 10% off) so customers have a reason to use the code.$h$, array[$h$Open Results & customer codes from your dashboard.$h$, $h$Type the code a customer shows you and log it.$h$, $h$Or create a staff link so counter staff can log codes on their phones without a HILLink login.$h$]::text[], $h$business$h$, $h$live$h$, $h$customer_codes$h$, array[$h$customer code$h$, $h$promo code$h$, $h$redeem$h$, $h$staff link$h$, $h$log code$h$, $h$redemption$h$, $h$track customers$h$]::text[], array[$h$How do I track customers from athletes?$h$, $h$How do my staff log codes?$h$]::text[], array[$h$monthly-results-report$h$]::text[], true, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$monthly-results-report$h$, $h$results$h$, $h$How do I see my results?$h$, $h$Open Results & customer codes on your dashboard. For each month you'll see customers from athletes, cost per customer, approved posts, order totals and Instagram reach.$h$, $h$The report includes:
- customers brought in by athletes
- cost per customer (athlete pay plus your plan price)
- posts approved
- order totals your staff entered
- Instagram reach, where the athlete's account is connected
- a breakdown by campaign and your top athletes

Pick a month at the top. Use **Print / save PDF** to keep a copy.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$results_report$h$, array[$h$results$h$, $h$roi$h$, $h$report$h$, $h$customers$h$, $h$cost per customer$h$, $h$analytics$h$, $h$reach$h$, $h$pdf$h$]::text[], array[$h$Is HILLink working for my business?$h$, $h$How do I measure ROI?$h$]::text[], array[$h$customer-codes-for-businesses$h$]::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$restricted-business-categories$h$, $h$business-account$h$, $h$Which businesses can't use HILLink?$h$, $h$Businesses in categories that NIL rules bar athletes from promoting can't post campaigns: alcohol, tobacco and vape, cannabis and CBD, betting, adult entertainment, firearms, and supplements.$h$, $h$You pick your business category when you set up your profile. Restricted categories can't be saved.

Some schools also have exclusive sponsors in certain categories. Athletes from those schools can't join campaigns from businesses in those categories, so a few athletes may not be able to join your campaign.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$compliance$h$, array[$h$restricted$h$, $h$category$h$, $h$alcohol$h$, $h$vape$h$, $h$cbd$h$, $h$betting$h$, $h$supplements$h$, $h$not allowed$h$, $h$banned$h$]::text[], array[$h$Why can't I pick my business category?$h$, $h$Can a bar use HILLink?$h$]::text[], '{}'::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz),
  ($h$managing-help-articles$h$, $h$internal$h$, $h$Managing Help Center articles$h$, $h$Edit articles at /admin/help. Customers only see live articles written for their account type; everything else stays admin-only.$h$, $h$## Who sees what
- Athletes: live articles for Athletes or Both.
- Businesses: live articles for Businesses or Both.
- Admins: everything, including drafts, planned features and Admins only notes.

The database enforces this from the reader's own account, so the future support agent can only ever retrieve what that user may read.

## Publishing checklist
- Describe only what the app does today. Planned features stay in planned status.
- Never put internal strategy, pricing experiments, margins, business plans or roadmap in customer articles.
- Use the preview links at the top of the Help Center to check what athletes and businesses see.
- Don't change a live article's URL name: emails and notifications link to it.

## Welcome email links
- Athletes: /help/getting-started/athlete-start-here
- Businesses: /help/getting-started/business-start-here
- Either (sends each person to their own guide): /help/start-here$h$, '{}'::text[], $h$admin$h$, $h$live$h$, $h$help_center$h$, array[$h$admin$h$, $h$help center$h$, $h$articles$h$, $h$publish$h$, $h$edit$h$, $h$knowledge base$h$]::text[], '{}'::text[], '{}'::text[], false, false, 0, '2026-09-27T00:00:00.000Z'::timestamptz)
on conflict (slug) do nothing;
