-- Help Center article updates. Generated by scripts/generate-help-seed.ts from lib/help/seed-content.ts; don't edit by hand.
-- Run after 20260928000610_help_center_seed.sql. Adds new articles and rewrites changed ones, but never
-- touches an article an admin has edited in the editor (updated_by is set). Safe to run again.

insert into public.help_articles
  (slug, category, title, short_answer, body, steps, audience, status, feature, keywords, question_variants, related_slugs, featured, escalation_required, sort_order, last_verified_at)
values
  ($h$how-to-submit-proof$h$, $h$proof-approval$h$, $h$How do I submit proof?$h$, $h$In My Campaigns, paste the link to your live post in the Proof URL box, add any notes, and choose Submit Proof.$h$, $h$You can submit proof once the business has accepted you. Double-check your link before you submit.

There's no screenshot upload. The business checks your live post through the link, so make sure it's public and shows everything the campaign asks for, including #ad.

If the business asks for changes, fix your post, paste the new link, and choose **Submit Again**.

If you post on Instagram and your account is connected, HILLink also pulls your post's stats (likes, comments, reach). Use **Sync Diagnostics** to refresh them.$h$, array[$h$Publish your post, including #ad or the Paid partnership label.$h$, $h$Copy the link to the live post.$h$, $h$Open My Campaigns on your dashboard and find the campaign.$h$, $h$Paste the link in Proof URL and add notes if helpful.$h$, $h$Choose Submit Proof.$h$]::text[], $h$athlete$h$, $h$live$h$, $h$proof_submission$h$, array[$h$proof$h$, $h$submit$h$, $h$link$h$, $h$url$h$, $h$upload$h$, $h$post link$h$, $h$screenshot$h$]::text[], array[$h$Where do I upload my post?$h$, $h$How do I show I posted?$h$, $h$How do I send my post link?$h$]::text[], array[$h$what-happens-after-i-submit-proof$h$, $h$campaign-requirements-explained$h$]::text[], true, false, 1, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$what-happens-after-i-submit-proof$h$, $h$proof-approval$h$, $h$What happens after I submit proof?$h$, $h$The business reviews your proof. If they approve it, you're paid and earn XP. If they don't review it within the campaign's review window (72 hours by default), it's approved automatically once your pay is funded.$h$, $h$## If the business approves
You get a notification, your pay is sent to your Stripe account, and you earn XP for completing the campaign. [When do I get paid?](/help/payments/when-do-i-get-paid)

## If the business doesn't respond
Proof that waits longer than the campaign's review window is approved automatically. The window is 72 hours by default and never shorter than 24 hours. This only happens once the business has funded your pay, and not while a dispute is open.

## If the business asks for changes
You'll get a notification and the campaign shows **Needs changes** in My Campaigns. Check the campaign requirements, fix your post, then paste the new link and choose **Submit Again**. The business reviews it again, with a new review window. If you think the decision is wrong, [contact HILLink](/help/disputes/disputes-and-problems).

After approval, the business may also [rate your work](/help/ratings/how-athlete-ratings-work).$h$, '{}'::text[], $h$athlete$h$, $h$live$h$, $h$proof_review$h$, array[$h$approval$h$, $h$approved$h$, $h$rejected$h$, $h$review$h$, $h$waiting$h$, $h$auto approve$h$, $h$72 hours$h$, $h$pending proof$h$, $h$resubmit$h$, $h$needs changes$h$, $h$fix$h$]::text[], array[$h$How long does approval take?$h$, $h$Why hasn't my proof been approved?$h$, $h$My proof was rejected$h$, $h$Can I resubmit my proof?$h$]::text[], array[$h$when-do-i-get-paid$h$, $h$how-athlete-ratings-work$h$, $h$disputes-and-problems$h$]::text[], true, false, 2, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$choosing-proof-requirements$h$, $h$campaign-requirements$h$, $h$What should I ask athletes to submit as proof?$h$, $h$Each campaign type comes with a proof checklist, such as a live post link and a post that says #ad. Athletes send proof as a link to their live post, so ask for things you can check by opening that link.$h$, $h$Examples from the built-in checklists:
- live post link
- post includes the required tags or mentions
- post says #ad or uses the Paid partnership label (always included, because the FTC requires it)
- post shows the visit (Dine and Post) or the product (Product Review)

Athletes send proof by pasting a link to their live post and adding notes. There's no screenshot upload. For campaigns with several posts, athletes put the extra links in the notes.

Clear directions get better posts. Say exactly what to mention, what to show and what customers should do.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_requirements$h$, array[$h$proof$h$, $h$requirements$h$, $h$checklist$h$, $h$deliverables$h$, $h$what to ask$h$, $h$directions$h$]::text[], array[$h$What proof should I require?$h$, $h$How do I write good directions?$h$]::text[], array[$h$how-to-review-proof$h$, $h$how-to-create-a-campaign$h$]::text[], false, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$how-to-review-proof$h$, $h$proof-approval$h$, $h$How do I review campaign proof?$h$, $h$When an athlete submits proof, open the campaign on your dashboard, choose View Proof, then Approve or Reject. Approving pays the athlete from the money you funded.$h$, $h$## Before you can approve
The athlete's pay must be funded. If it isn't, you'll see **Fund payment** first.

## If you don't review it
Proof you don't review within the campaign's review window (72 hours by default) is approved automatically and the athlete is paid. This only happens for funded work and never while a dispute is open. Unfunded work is never auto-approved; you'll get a reminder instead.

## Rejecting
Reject proof that doesn't meet your requirements. The athlete is notified and can fix their post and send it again. Their funded pay stays held until you approve, and the review window starts over when they resubmit. If you're not sure, [contact HILLink](/help/disputes/disputes-and-problems).

## After approving
You're asked to rate the athlete right away. You can also rate them later with **Rate Athlete**. [Rating athletes](/help/ratings/rating-athletes)

## Post stats
For Instagram posts, **Sync Diagnostics** shows likes, comments and reach when the athlete's account is connected.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$proof_review$h$, array[$h$review$h$, $h$approve$h$, $h$reject$h$, $h$proof$h$, $h$view proof$h$, $h$auto approve$h$, $h$72 hours$h$, $h$submission$h$, $h$resubmit$h$]::text[], array[$h$How do I approve a post?$h$, $h$What happens if I don't review proof?$h$]::text[], array[$h$paying-athletes$h$, $h$rating-athletes$h$, $h$after-an-athlete-is-approved$h$]::text[], true, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$after-an-athlete-is-approved$h$, $h$proof-approval$h$, $h$What happens when an athlete's work is approved?$h$, $h$The athlete is paid from the money you funded, earns XP, and their part of the campaign shows as completed. You can then rate them and track customers they bring in.$h$, $h$- **Payment**: the athlete's pay is sent to their Stripe account. If their payout account isn't set up yet, a **Pay athlete** button lets you send it later.
- **Ratings**: you're asked to rate the athlete from 1 to 5 stars as soon as you approve. [Rating athletes](/help/ratings/rating-athletes)
- **Results**: customers who use the athlete's code keep counting in your [monthly results](/help/results/monthly-results-report).$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_completion$h$, array[$h$completed$h$, $h$complete$h$, $h$done$h$, $h$finished$h$, $h$after approval$h$, $h$campaign completed$h$]::text[], array[$h$What happens when a campaign is completed?$h$, $h$What do I do after approving?$h$]::text[], array[$h$rating-athletes$h$, $h$monthly-results-report$h$]::text[], false, false, 1, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$rating-athletes$h$, $h$ratings$h$, $h$How do athlete ratings work?$h$, $h$After an athlete's work is approved, you can rate them from 1 to 5 stars and add a short review. Ratings help other businesses and shape the athlete's Hillink Score.$h$, $h$- When you approve an athlete's work, a rating window opens right away.
- To rate later, open the campaign on your dashboard (or in **Campaign History**), expand the athlete, and choose **Rate Athlete**.
- You can rate each athlete once per campaign.
- An athlete's average rating shows on their profile.
- Athletes whose average falls below 1.5 stars can't apply to new campaigns.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$ratings$h$, array[$h$rate$h$, $h$rating$h$, $h$stars$h$, $h$review athlete$h$, $h$feedback$h$]::text[], array[$h$How do I rate an athlete?$h$, $h$Where is the Rate Athlete button?$h$]::text[], array[$h$hillink-score-for-businesses$h$]::text[], false, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$business-plans$h$, $h$plans-billing$h$, $h$How do business plans work?$h$, $h$HILLink has four monthly plans. Your plan sets how many campaigns you can run at once, how many athletes each campaign can have, and the highest athlete tier you can work with.$h$, $h$## Plans
- **Starter**, $250/month: 2 open campaigns, up to 3 athletes each, athletes up to Silver
- **Growth**, $400/month: 5 open campaigns, up to 6 athletes each, athletes up to Gold
- **Scale**, $700/month: 10 open campaigns, up to 12 athletes each, athletes up to Platinum
- **Domination**, $1,200/month: 20 open campaigns, up to 20 athletes each, all tiers including Diamond

Choose your plan and billing details in **Settings**, then pay through Stripe's secure checkout. You need an active plan before you can post a campaign.

## Changing or cancelling your plan
- **Switch plans:** in Settings, pick a new tier and choose **Pay and Activate Tier**. Stripe charges or credits the difference right away.
- **Cancel, update your card or see invoices:** choose **Manage billing or cancel plan** in Settings. Without an active plan you can't post new campaigns.

## Athlete pay
Athlete pay isn't included in your plan. For each athlete you accept, you pay their campaign pay plus HILLink's 20% platform fee and card processing. [Paying athletes](/help/payments/paying-athletes)$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$subscriptions$h$, array[$h$plan$h$, $h$pricing$h$, $h$price$h$, $h$subscription$h$, $h$billing$h$, $h$starter$h$, $h$growth$h$, $h$scale$h$, $h$domination$h$, $h$cost$h$, $h$cancel$h$, $h$upgrade$h$, $h$downgrade$h$, $h$invoice$h$, $h$card$h$]::text[], array[$h$How much does HILLink cost?$h$, $h$What plan do I need?$h$, $h$How do I pay for HILLink?$h$, $h$How do I cancel my plan?$h$, $h$How do I change my plan?$h$]::text[], array[$h$paying-athletes$h$, $h$how-to-create-a-campaign$h$]::text[], true, false, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$paying-athletes$h$, $h$payments$h$, $h$How do athlete payments work?$h$, $h$When you accept an athlete, you fund their pay plus HILLink's 20% platform fee through Stripe. HILLink holds the money and sends the athlete's pay to them when you approve their work. If the athlete leaves or you remove them first, you're refunded.$h$, $h$## Funding
After you accept an athlete, choose **Fund payment**. The button shows the exact total before you pay. It covers:
- the athlete's pay (the athlete receives all of it)
- HILLink's platform fee: 20% of the athlete's pay
- card processing

For example, for a $100 athlete, you pay $100 plus a $20 fee, plus card processing. This is separate from your monthly plan.

## Paying out
When you approve the athlete's proof, their pay is sent to them automatically. If their payout account isn't ready yet, use **Pay athlete** later.

## Refunds
- If you remove an accepted athlete, or the athlete drops the campaign before approval, the money you funded is refunded.
- Money that has already been paid out to an athlete is not refunded.

## In-kind campaigns
If a campaign pays $0 (for example, a free meal), there's nothing to fund.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$campaign_payments$h$, array[$h$pay athletes$h$, $h$fund$h$, $h$funding$h$, $h$payment$h$, $h$refund$h$, $h$held$h$, $h$stripe$h$, $h$checkout$h$, $h$fee$h$, $h$platform fee$h$, $h$20%$h$, $h$commission$h$]::text[], array[$h$When do I pay athletes?$h$, $h$Do I get a refund if an athlete doesn't post?$h$, $h$What is Fund payment?$h$, $h$How much is HILLink's fee?$h$]::text[], array[$h$how-to-review-proof$h$, $h$removing-an-athlete$h$]::text[], true, true, 0, '2026-09-28T00:00:00.000Z'::timestamptz),
  ($h$cancelling-a-campaign$h$, $h$campaign-problems$h$, $h$Can I cancel a campaign?$h$, $h$Yes, as long as no athlete's work on it has been approved yet. Choose Cancel Campaign on your dashboard. Any athlete pay you funded is refunded and the athletes are notified.$h$, $h$- Cancelling removes the campaign and everyone who applied or joined it.
- Athletes who applied, were accepted or had sent proof get a notification.
- Money you funded for athletes is refunded to you through Stripe.
- Once any athlete's work on the campaign has been approved, it can't be cancelled.

To stop working with just one athlete, [remove them](/help/campaign-problems/removing-an-athlete) instead.$h$, '{}'::text[], $h$business$h$, $h$live$h$, $h$cancel_campaign$h$, array[$h$cancel$h$, $h$delete campaign$h$, $h$stop campaign$h$, $h$end campaign$h$, $h$remove campaign$h$, $h$refund$h$]::text[], array[$h$How do I cancel a campaign?$h$, $h$How do I delete a campaign?$h$, $h$Can I stop my campaign?$h$]::text[], array[$h$removing-an-athlete$h$, $h$paying-athletes$h$]::text[], false, false, 1, '2026-09-28T00:00:00.000Z'::timestamptz)
on conflict (slug) do update set
  category = excluded.category,
  title = excluded.title,
  short_answer = excluded.short_answer,
  body = excluded.body,
  steps = excluded.steps,
  audience = excluded.audience,
  status = excluded.status,
  feature = excluded.feature,
  keywords = excluded.keywords,
  question_variants = excluded.question_variants,
  related_slugs = excluded.related_slugs,
  featured = excluded.featured,
  escalation_required = excluded.escalation_required,
  sort_order = excluded.sort_order,
  last_verified_at = excluded.last_verified_at
where help_articles.updated_by is null
  and (help_articles.category, help_articles.title, help_articles.short_answer, help_articles.body, help_articles.steps, help_articles.audience, help_articles.status, help_articles.feature, help_articles.keywords, help_articles.question_variants, help_articles.related_slugs, help_articles.featured, help_articles.escalation_required, help_articles.sort_order, help_articles.last_verified_at)
      is distinct from (excluded.category, excluded.title, excluded.short_answer, excluded.body, excluded.steps, excluded.audience, excluded.status, excluded.feature, excluded.keywords, excluded.question_variants, excluded.related_slugs, excluded.featured, excluded.escalation_required, excluded.sort_order, excluded.last_verified_at);
