export const REASON_MESSAGES: Record<string, string> = {
  campaign_not_found: "Campaign not found",
  campaign_not_active: "This campaign is not accepting applications",
  auto_accept_disabled: "Auto-accept is not enabled for this campaign",
  no_slots: "This campaign is full",
  auto_accept_locked: "Applications are closed within 12 hours of campaign start",
  athlete_profile_not_found: "Athlete profile not found",
  not_verified: "Your account must be verified to apply",
  flagged: "Your account is not eligible to apply",
  tier_insufficient: "You do not meet the minimum tier for this campaign",
  outside_radius: "You are outside the campaign's acceptance radius",
  already_applied: "You have already applied to this campaign",
  duplicate_application: "You have already applied to this campaign",
  location_missing: "Your profile is missing location data",
  campaign_location_missing: "This campaign has no location set",
  compliance_required: "Confirm your eligibility (age, visa and school disclosure) before joining campaigns.",
  visa_not_cleared: "Student visas usually don't allow paid NIL work in the US. Check with your school's international office, then update your eligibility.",
  school_conflict: "Your school has an exclusive deal in this business's category, so you can't join this campaign.",
  business_restricted: "This business is in a category athletes can't promote.",
  instagram_not_verified: "Connect your Instagram with Instagram login in Settings before joining campaigns.",
};
